// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVfKSamzjRaIjeEzDTlbYAwx8P4CkDDSI',
    appId: '1:763710110115:web:8365067f0bb22e43268216',
    messagingSenderId: '763710110115',
    projectId: 'lab3-c5787',
    authDomain: 'lab3-c5787.firebaseapp.com',
    storageBucket: 'lab3-c5787.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeVaqFCP-LoOaUOEBxP4CpRhpcolcvPvM',
    appId: '1:763710110115:android:bfa306dcc69ca7f0268216',
    messagingSenderId: '763710110115',
    projectId: 'lab3-c5787',
    storageBucket: 'lab3-c5787.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABnAWxOtEMMtzawPS2nTebW5Lt9-W1Ikw',
    appId: '1:763710110115:ios:bc47c08639dd5712268216',
    messagingSenderId: '763710110115',
    projectId: 'lab3-c5787',
    storageBucket: 'lab3-c5787.appspot.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABnAWxOtEMMtzawPS2nTebW5Lt9-W1Ikw',
    appId: '1:763710110115:ios:6eea2cdd82b29fa0268216',
    messagingSenderId: '763710110115',
    projectId: 'lab3-c5787',
    storageBucket: 'lab3-c5787.appspot.com',
    iosBundleId: 'com.example.lab3.RunnerTests',
  );
}
